openvpn:
  image: shole/rtorrent-openvpn
  privileged: true
  ports:
    - "9091:9091"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /your/storage/path/:/download
    - /your/watch/path/:/watch
    - /your/config/path/:/config
    - /your/ovpn/files/:/vpn

    environment:
    OPENVPN_PROVIDER: PIA
    OPENVPN_USERNAME: username
    OPENVPN_PASSWORD: password
